### ISSUE TITLE
"Parallelized" actions question

### ISSUE THREAD

**Issue by benhawkinsicon** [caesuric/mountain-goap#15]
I am experimenting with agents that understand how to use multiple managed resources to execute on goals.

I would like to avoid resource-scoped agents for now. There are occasionally times when the agent needs to perform actions in parallel (simultaneously run health check on 3 subsystems). I have identified a pretty ugly solution which allows marking actions as `parallel`, and enables the plan to execute these actions in quick succession, while waiting for them all to finish.

The code below uses execution status to indicate work is only done on the first call to the executor while tracking the lifecycle of the action and still letting the plan execute on neighboring `parallel` nodes. 

I don't understand fully how the planner utilizes `ExecutionStatus.NotYetExecuted`, but I am assuming this would have unwanted consquences. The current behavior works but I am wondering your thoughts on best/worse ways of achieving this.

```
public static ExecutionStatus MockExecutor(Agent agent, Action action, string lifecycleKey, int seconds=1, bool parallel=false, double failRate=0)
{
    /// execute first time
    if (!agent.State.ContainsKey(lifecycleKey))
    {
        agent.State[lifecycleKey] = DateTime.Now;
        return ExecutionStatus.Executing;
    }

    DateTime startTime = (DateTime)agent.State[lifecycleKey]!;
    if ((DateTime.Now - startTime).TotalSeconds > seconds)
    {
        /// clean up
        agent.State.Remove(lifecycleKey);
        return MaybeFail(failRate) ? ExecutionStatus.Failed : ExecutionStatus.Succeeded;
    }
    
    /// indicate not executing
    return parallel ? ExecutionStatus.NotYetExecuted : ExecutionStatus.Executing;
}
```

**Comment by caesuric** [comment]
> I don't understand fully how the planner utilizes ExecutionStatus, but I am assuming this would have many unwanted consquences. The current behavior works as expected, but I am wondering your thoughts on best/worse ways of achieving this.

When ExecutionStatus is Success, the action is removed from the action chain and the postconditions are set. When it's Failed, it is removed from the chain and the postconditions are NOT set. When it's Executing, it stays in the chain and executes again on the next Step. This last is meant for actions that take multiple steps to execute.

> I am experimenting with using this library to create a "machine agent" which understands how to use multiple managed resources/subsystems to execute on goals.

It's so funny that you raise this point because this is something I've thought about a lot even though I haven't implemented it in MountainGoap yet. The underlying system is supposed to return a series of parallel action chains, in fact, even though the array always contains 0 or 1 chain right now since I haven't gotten to this yet.

I think the ultimate best way to handle this would be to incorporate some kind of resourcing system into MountainGoap to limit parallel actions in a semi-realistic fashion.

Say for example, we have an agent representing a human being. We define the agent as having the resources "LeftLeg" "RightLeg" "LeftArm" "RightArm" etc. An action that uses the agent's arms should be able to execute in parallel to an action that uses the agent's legs, but the agent shouldn't be able to, for instance, walk and kick something at the same time, because walking requires both legs and kicking requires at least one.

Things that would be needed to make a system like this a reality:
1. A way to define *resources*
2. A way to stipulate that an action requires one or more *resources*
3. A way to set the agent to simple or parallel execution modes (not everyone is going to want or need the complexities of this system)

Open questions:
1. How are resources defined? Are they simply string tags that you require or don't require? Are they numeric quantities for interchangeable resources? (i.e. instead of LeftLeg and RightLeg, I have legs: 2 and can use 1 leg for some actions and 2 for others; or I have 64 GB of RAM and I need 16 to perform a specific task)
2. Can resource requirements be more complex than simply needing X? Can I need X *or* Y, for example? How complex should this get?

Would be interested to hear your thoughts on this approach vs. what you have already implemented. I'm happy to make an attempt at something like this at some point in the near future, especially if someone actually needs it for their project. :wink:

**Comment by benhawkinsicon** [comment]
Thanks for the reply! Supporting managed resources out-of-the-box sounds both interesting and intimidating. 

I am torn in that my agent’s scope is intended to reflect that of a “smart operator” which is executing on high-enough level machine actions, while keeping many aspects of resource management in a type of firmware layer (or other) which distills relevant info into the planner’s state via sensor. So, an operator would occasionally want to trigger a “health” check on multiple components at the same-ish time. In actuality, fast-sequential is all I need (faux parallelization) as opposed to requiring all to start on the same loop.

Your solution regarding resource management seems more appropriate if I reconsider the scope of the agent. I wouldn't discourage further exploration of this path, but I also believe that resource management generally might not require planning, leaning on FSMs or similar. In other words, it might be leaking certain larger-than-GOAP architectural opinions into the library (which isn’t necessarily bad!).

I am curious what a more minimal solution could look like, either using existing principles or smaller changes, so as to maximize flexibility.

**Comment by benhawkinsicon** [comment]
Oh, when describing ExecutionStatus, you didn't mention `NotYetExecuted` which is the status I am using for my current hack - it might help to hear your take on what correct usage of this status looks like

**Comment by benhawkinsicon** [comment]
```
public class CheckSys1Health : ActionBase 
{
    public CheckSys1Health() : base(
        name: "CheckSys1Health",
        description: "Checks the health of a specific (1) sub-system, the agent is allowed to do other things of equal cost",
        cost: 3001,
        preconditions: new MultiPredicate(new List<object?>{
            Knowledge.Sys1Initialized(true)!,
            Knowledge.Sys1Healthy(false)!,
        }),
        effects: Knowledge.Sys1Healthy(true),
        executor: (agent, action) => F.MockExecutor(
            agent, action, "sys1_checked_at", 1, true, failRate:.5)
    ) {}
}
```

Example code (minus the cost)

**Comment by caesuric** [comment]
> Oh, when describing ExecutionStatus, you didn't mention NotYetExecuted which is the status I am using for my current hack - it might help to hear your take on what correct usage of this status looks like (i.e. "never manually set this")

NotYetExecuted isn't checked for or referenced anywhere except at action instantiation. It's the default value for ExecutionStatus and indicates that the action hasn't been run. Probably shouldn't ever manually set it, but if it works, it works.

> Even though I mentioned "managed resources", I am having some success just predicating off of the blackboard with statuses and such. Do parallel actions need a resourcing system to work?

Strictly speaking, no! But in theory you might want limits to the parallelism which is where resourcing could come in. I personally can't think of many agent-based scenarios where I would desire unlimited parallelism.

For the rest, I'm not sure I 100% follow. Certainly if you prefer not to use a resourcing system, it seems like you have found a modification of the library that works well for you, and I always encourage people to use things that work for them. But I'm not sure I understand the merits of the approach over a resource-limited approach, though I'm sure they exist. It seems to me like there might be factors specific to your needs that drive this approach, which is completely reasonable. I would like to understand those factors better so I can help, but it's up to you whether or not it's worth explaining the intricacies of your scenario to me. 😄

**Comment by benhawkinsicon** [comment]
Yea so my requirements and suggested solution should probably be separately considered as I don't see myself offering a "correct" solution, and can only speculate on what _might_ work with A*.

Basic RPG Example:

- There is a "blacksmith" agent which interacts with a hammer and anvil to achieve goals. 
- There is a durability factor to both the hammer and anvil which decrements over time.
- Every morning, regardless of durability factors, the blacksmith wants to repair all of his objects before starting the day
- RepairXX actions exist for each tool
- He can repair tools simultaneuosly

That is really it for my requirements.

I guess I could introduce an additional "RepairAll" action which costs more than the individual actions. This doesn't work great for repairing 2-out-of-3 tools, while that type of logic is handled gracefully by a planner, except that nodes are executed asynchronously.

--

Then you have, my _initial thought_ where the "Parallelized" question comes from, which was in hopes to avoid an additional RepairAll action, but rather let the planner determine it should hit each repair action synchronously (or in quick succession). Is this anti-GOAP?

So, marking each individual repair action as "parallel" means that the planner will ultimately initiate all repair actions in quick succession (still 1 pass per node), wait for them all to finish, then proceed. The 2 mechanisms I assume A* would need are 

> I personally can't think of many agent-based scenarios where I would desire unlimited parallelism.
- a mechanism for limiting parallelism. Could be `parallel` boolean on the action which changes behavior of `ExecutionStatus.executing` OR `ExecutionStatus.parallelExecution` might be better so an action can conditionally support both

> An update to the planning engine allowing it to ...

- determine that the current node supports parallel execution, thus seeking other nodes whose preconditions are satisfied, and also marked as parallel. I am not sure if preconditions + parallel is enough, you could also require that the other nodes are "siblings" with an equal cost to the currently executing parallel action.

As far as postconditions / action chain is concerned, I would assume `ExecutionStatus.parallelExecution` mimics `.executing`

**Comment by benhawkinsicon** [comment]
Maybe something like this, keeping patterns found in the library

```
ParallelAction repairAction = new ParallelAction(
    // called for each permutation, all must Succeed
    executor: (Agent agent, Action action, string permutation) => {
        Console.WriteLine("repairing " + permutation);
        // take some time
        return ExecutionStatus.Succeeded;
    },
    permutationSelectors: new Dictionary<string, PermutationSelectorCallback> {
        { "toolId", PermutationSelectorGenerators.SelectFromCollectionInState<string>("tools") }
    },
    preconditions: (string permutation) => { },
    postconditions: (string permutation) => { }
);
```

**Comment by caesuric** [comment]
That does complicate things, yes. I'll give this some additional thought.
